-- =============================================================================
-- MySQL Exercise 5 - Step 10
-- Author: Preston Furulie
-- Database: my_guitar_shop
-- Description: Restore the database to its original state by running the
--              create_my_guitar_shop.sql script from the mgs_ex_starts
--              directory. Open that script in MySQL Workbench and execute
--              it to reset all data modified during this exercise.
-- =============================================================================

-- To restore the database:
-- 1. Open MySQL Workbench
-- 2. Go to File > Open SQL Script
-- 3. Navigate to the mgs_ex_starts directory
-- 4. Open create_my_guitar_shop.sql
-- 5. Execute the script (lightning bolt icon or Ctrl+Shift+Enter)
--
-- This will drop and recreate all tables with the original data,
-- undoing all INSERT, UPDATE, and DELETE changes made in Steps 1-9.
