-- =============================================================================
-- MySQL Exercise 5 - Step 1
-- Author: Preston Furulie
-- Database: my_guitar_shop
-- Description: INSERT a new row into the Categories table with
--              category_name = 'Brass'. The category_id column is
--              auto-generated by MySQL (AUTO_INCREMENT).
-- =============================================================================

USE my_guitar_shop;

-- Insert the new category; category_id is automatically generated
INSERT INTO categories (category_name)
VALUES ('Brass');

-- Verify the insert was successful
SELECT *
FROM categories;
